export const GET_SEXES_DICTIONARY_REQUEST = 'app/GET_SEXES_DICTIONARY_REQUEST';
export const GET_SEXES_DICTIONARY_SUCCESS = 'app/GET_SEXES_DICTIONARY_SUCCESS';
export const GET_SEXES_DICTIONARY_FAILED = 'app/GET_SEXES_DICTIONARY_FAILED';
