import { withStyles } from '@material-ui/core/styles';
import Typography from '@material-ui/core/Typography';

export const ParagraphWrapper = withStyles(() => ({
  root: {
    '&.textWrapperTitle': {
      fontFamily: 'NoahBold',
      fontSize: '20px',
      lineHeight: '36px',
      color: '#213442',
    },
    '&.textWrapperText': {
      fontFamily: 'NoahRegular',
      fontSize: '16px',
      lineHeight: '22px',
      color: '#213442',
    },
    '&.navListItem': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '18px',
      lineHeight: '24px',
      color: 'rgba(33, 52, 66, 0.54)',
    },
    '&.chartInfoDataRangeMulti': {
      fontSize: '18px',
      lineHeight: '24px',
      marginLeft: '11px',
      marginTop: '26px',
      fontFamily: 'NoahRegular',
      color: '#213442',
    },
    '&.terms': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '18px',
      lineHeight: '24px',
      color: '#213442',
      marginRight: '15px',
    },
    '&.chartInfoDataSegmentMulti': {
      fontSize: '24px',
      lineHeight: '38px',
      whiteSpace: 'nowrap',
      marginLeft: '11px',
    },
    '&.chartInfoDataSegment': {
      fontSize: '82px',
      lineHeight: '68px',
      marginTop: '28px',
      color: '#213442',
      fontFamily: 'NoahRegular',
    },
    '&.loadFileText': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '21px',
      lineHeight: '28px',
      color: '#213442',
      margin: 0,
    },
    '&.printDocumentText': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '21px',
      lineHeight: '28px',
      color: '#213442',
      maxWidth: '484px',
      marginRight: '30px',
    },
    '&.warningText': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '21px',
      lineHeight: '28px',
      color: '#213442',
      maxWidth: '812px',
    },
    '&.userInfo': {
      fontFamily: 'NoahBold',
      fontSize: '20px',
      lineHeight: '30px',
    },
    '&.navigateItem': {
      fontSize: '24px',
      lineHeight: '36px',
      fontFamily: 'NoahBold',
    },
    '&.sliderCite': {
      fontFamily: 'IBM Plex Sans',
      marginBottom: '1rem',
      fontSize: '14px',
      lineHeight: '20px',
      fontStyle: 'normal',
      fontWeight: 'normal',
      color: 'rgba(255, 255, 255, 0.75)',
    },
    '&.sliderCiteAuthor': {
      fontFamily: 'IBM Plex Sans',
      margin: '0',
      fontSize: '18px',
      lineHeight: '20px',
      fontStyle: 'normal',
      fontWeight: 'normal',
      color: 'rgba(255, 255, 255, 0.87)',
    },
    '&.sliderCitePosition': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '12px',
      color: 'rgba(255, 255, 255, 0.75)',
    },
    '&.forgotText': {
      fontFamily: 'NoahBold',
      fontStyle: 'normal',
      fontWeight: 'bold',
      fontSize: '14px',
      lineHeight: '20px',
      color: '#213442',
      opacity: 0.54,
      marginTop: '16px',
    },
    '&.text': {
      margin: '0 0 0 auto',
      fontFamily: 'IBM Plex Sans',
      fontStyle: 'normal',
      fontWeight: 'normal',
      lineHeight: '24px',
      fontSize: '14px',
      color: 'rgba(13, 12, 34, 0.54)',
    },
    '&.phone': {
      margin: '0 0 0 auto',
      fontFamily: 'IBM Plex Sans',
      fontStyle: 'normal',
      fontWeight: 'normal',
      lineHeight: '24px',
      fontSize: '20px',
      color: 'rgba(13, 12, 34, 0.54)',
    },
    '&.statisticsItemText': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '18px',
      lineHeight: '20px',
      fontWeight: '200',
      color: 'white',
    },
    '&.statisticsItemCount': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '96px',
      lineHeight: '0.8',
      fontWeight: '200',
      color: 'white',
    },
    '&.nameWeekDay': {
      fontSize: '18px',
      lineHeight: '24px',
      fontWeight: '200',
      marginBottom: '4px',
      fontFamily: 'IBM Plex Sans',
    },
    '&.dateToDay': {
      fontSize: '14px',
      lineHeight: '20px',
      fontWeight: '200',
      marginBottom: '8px',
      fontFamily: 'IBM Plex Sans',
    },
    '&.depositMainInfo': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '14px',
      lineHeight: '28px',
      color: '#213442',
      margin: 0,
    },
    '&.time': {
      fontSize: '64px',
      lineHeight: '64px',
      fontWeight: '200',
      fontFamily: 'IBM Plex Sans',
    },
    '&.servicesListItemTitle': {
      fontFamily: 'NoahRegular',
      fontSize: '24px',
      lineHeight: '20px',
      fontWeight: '500',
      color: '#213442',
      marginBottom: '5px',
    },
    '&.servicesListItemText': {
      fontFamily: 'NoahRegular',
      fontSize: '12px',
      lineHeight: '14px',
      fontWeight: '200',
      color: '#213442',
    },
    '&.status': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '12px',
      lineHeight: '14px',
      weight: '400',
      color: '#213442',
      margin: 0,
    },
    '&.taskTitle': {
      fontSize: '18px',
      lineHeight: '20px',
      fontWeight: 'bold',
      color: '#213442',
      marginBottom: '4px',
      fontFamily: 'NoahBold',
    },
    '&.taskTagListItemText': {
      fontSize: '10px',
      lineHeight: '14px',
      fontWeight: 'normal',
      color: '#213442',
    },
    '&.documentInfoCount': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '25px',
      lineHeight: '28px',
      color: '#213442',
      margin: 0,
      marginBottom: '30px',
    },
    '&.depositTitle': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '25px',
      lineHeight: '28px',
      color: '#213442',
      margin: 0,
    },
    '&.btnDelText': {
      fontFamily: 'IBM Plex Sans',
      fontSize: '14px',
      lineHeight: '12px',
      color: '#E50000',
      borderBottom: '1px solid #E50000',
    },
    '&.documentInfoName': {
      fontFamily: 'NoahRegular',
      fontSize: '16px',
      lineHeight: '14px',
      color: '#213442',
      margin: 0,
      marginBottom: '16px',
      '& span': {
        fontFamily: 'NoahBold',
        fontSize: '16px',
        lineHeight: '14px',
        color: '#213442',
        margin: 0,
        marginBottom: '16px',
      },
    },
    '&.menuItemChild': {
      marginLeft: '10px',
    },
  },
}))(Typography);

// export const TitleWrapper = withStyles(() => ({
//   root: {
//     marginBottom: '10px',
//     '& h3': {
//       fontFamily: 'NoahBold',
//       fontSize: '40px',
//       lineHeight: '72px',
//       color: '#213442',
//       margin: 0,
//     },
//   },
// }))(Box);
